"""Data models and schemas for the Project Ideator Agent and A2UI contracts."""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class GrillStage(str, Enum):
    """The 5 stages of the Project Ideation Grilling Flow."""
    PROBLEM_AND_GOAL = "problem_and_goal"
    TARGET_AUDIENCE = "target_audience"
    PAIN_AND_ALTERNATIVES = "pain_and_alternatives"
    SCOPE_AND_NON_GOALS = "scope_and_non_goals"
    PRD_DRAFT = "prd_draft"

    @property
    def stage_number(self) -> int:
        mapping = {
            GrillStage.PROBLEM_AND_GOAL: 1,
            GrillStage.TARGET_AUDIENCE: 2,
            GrillStage.PAIN_AND_ALTERNATIVES: 3,
            GrillStage.SCOPE_AND_NON_GOALS: 4,
            GrillStage.PRD_DRAFT: 5,
        }
        return mapping[self]

    @property
    def display_title(self) -> str:
        mapping = {
            GrillStage.PROBLEM_AND_GOAL: "1. Core Problem & Goal",
            GrillStage.TARGET_AUDIENCE: "2. Target Audience & Persona",
            GrillStage.PAIN_AND_ALTERNATIVES: "3. Current Pain & Workarounds",
            GrillStage.SCOPE_AND_NON_GOALS: "4. Scope & Non-Goals",
            GrillStage.PRD_DRAFT: "5. PRD Review & Export",
        }
        return mapping[self]

    @property
    def next_stage(self) -> GrillStage | None:
        order = [
            GrillStage.PROBLEM_AND_GOAL,
            GrillStage.TARGET_AUDIENCE,
            GrillStage.PAIN_AND_ALTERNATIVES,
            GrillStage.SCOPE_AND_NON_GOALS,
            GrillStage.PRD_DRAFT,
        ]
        idx = order.index(self)
        if idx < len(order) - 1:
            return order[idx + 1]
        return None


class PRDSpec(BaseModel):
    """Structured Product Requirement Document specification."""
    title: str = Field(..., description="Project Title")
    tagline: str = Field(default="", description="One sentence summary of what, for whom, why now")
    target_persona: str = Field(..., description="Specific target user and real-world role")
    problem_statement: str = Field(..., description="The core problem and why current solutions fail")
    pain_points: list[str] = Field(default_factory=list, description="Specific friction points experienced today")
    core_features: list[str] = Field(default_factory=list, description="Key functional requirements for first slice")
    non_goals: list[str] = Field(default_factory=list, description="Explicitly cut / out of scope items")
    success_metrics: list[str] = Field(default_factory=list, description="Observable criteria proving success")
    riskiest_assumption: str = Field(default="", description="The single assumption that kills the project if false")
    first_slice_milestone: str = Field(default="", description="Concrete deliverable built by end of week 1")
    tech_stack_notes: list[str] = Field(default_factory=list, description="Recommended architectural components")

    def to_markdown(self) -> str:
        """Render the PRD as clean GitHub-flavored markdown."""
        pain_points_md = "\n".join([f"- {p}" for p in self.pain_points]) or "- Standard workflow friction"
        features_md = "\n".join([f"- **{f}**" if ":" not in f else f"- **{f.split(':', 1)[0]}**: {f.split(':', 1)[1]}" for f in self.core_features]) or "- Core capability slice"
        non_goals_md = "\n".join([f"- [x] *CUT:* {ng}" for ng in self.non_goals]) or "- Advanced integrations deferred to Phase 2"
        metrics_md = "\n".join([f"- [ ] {m}" for m in self.success_metrics]) or "- User completes core task in < 2 minutes"
        tech_md = "\n".join([f"- {t}" for t in self.tech_stack_notes]) or "- Standard cloud agent stack"

        return f"""# Product Requirements Document (PRD)

## Project: {self.title}

> **Commitment:** {self.tagline}

---

### 1. Executive Summary & Persona
- **Target Persona:** {self.target_persona}
- **Problem Statement:** {self.problem_statement}

### 2. Current Pain Points & Friction
{pain_points_md}

### 3. First Slice Scope (Core Features)
{features_md}

### 4. Non-Goals & Cuts (Out of Scope for V1)
{non_goals_md}

### 5. Observable Success Metrics ("Done Looks Like")
{metrics_md}

### 6. Risk & First Milestone
- **Riskiest Assumption:** {self.riskiest_assumption or "Adoption by target persona"}
- **First Milestone (Day 1 / Week 1):** {self.first_slice_milestone or "Working interactive prototype with test data"}

### 7. Technical & Architecture Notes
{tech_md}

---
*Generated by Project Ideator Agent via A2UI Protocol*
"""


class IdeationSession(BaseModel):
    """Session state for the ideation interview."""
    session_id: str = Field(default="default_session")
    project_name: str = Field(default="New Project")
    current_stage: GrillStage = Field(default=GrillStage.PROBLEM_AND_GOAL)
    answers: dict[str, str] = Field(default_factory=dict)
    options_offered: dict[str, list[str]] = Field(default_factory=dict)
    prd_spec: PRDSpec | None = Field(default=None)
    prd_markdown: str = Field(default="")
    is_completed: bool = Field(default=False)
    exported_file_path: str | None = Field(default=None)


class UIAction(BaseModel):
    """User interaction event received from an A2UI component."""
    event_name: str
    selected_option: str | None = None
    freeform_text: str | None = None
    stage: str | None = None
